---
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: xnopresources.nop.example.org
spec:
  compositeTypeRef:
    apiVersion: nop.example.org/v1alpha1
    kind: XNopResource
  mode: Pipeline
  pipeline:
  - step: loop
    functionRef:
      name: loop
    input:
      valuesXrPath: "spec.namespaces"
      namePrefix: "ns-"
      paths:
        - spec.forProvider.manifest.metadata.name
        - spec.providerConfigRef.name = spec.id
      resources:
        - base:
            apiVersion: kubernetes.crossplane.io/v1alpha1
            kind: Object
            spec:
              forProvider:
                manifest:
                  apiVersion: v1
                  kind: Namespace

