---
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: xnopresources.nop.example.org
spec:
  compositeTypeRef:
    apiVersion: nop.example.org/v1alpha1
    kind: XNopResource
  mode: Pipeline
  pipeline:
  - step: loop
    functionRef:
      name: dot-loop
    input:
      valuesXrPath: "spec.namespaces"
      namePrefix: "ns-"
      paths:
        - "spec.forProvider.manifest.metadata.name"
      # namespaces:
      #   - dev
      #   - production
      resources:
        - base:
            apiVersion: kubernetes.crossplane.io/v1alpha1
            kind: Object
            spec:
              forProvider:
                manifest:
                  apiVersion: v1
                  kind: Namespace
          patches:
          - fromFieldPath: spec.id
            toFieldPath: metadata.name
            transforms:
            - string:
                fmt: '%s-ns-production'
              type: string
          - fromFieldPath: spec.id
            toFieldPath: spec.providerConfigRef.name
