---
apiVersion: pkg.crossplane.io/v1beta1
kind: Function
metadata:
  name: loop
  annotations:
    render.crossplane.io/runtime-docker-pull-policy: Always
spec:
  package: 'index.docker.io/bmutziu/crossplane-function-loop:v0.0.11'
